
import sqlite3
from sqlite3 import Error 

def create_connection(db_file):
    pass 